# prj.conf per native_sim su Zephyr 4.4
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y

CONFIG_CBPRINTF_FP_SUPPORT=y


# ------------------ Flash e Storage ------------------
# 1. Abilita il supporto hardware per la memoria flash
CONFIG_FLASH=y

# 2. Abilita il driver del simulatore di flash
CONFIG_FLASH_SIMULATOR=y

# 3. Abilita il layout delle pagine di flash (richiesto da FCB)
CONFIG_FLASH_PAGE_LAYOUT=y

# 4. Abilita la mappa della memoria flash (richiesto da FCB)
CONFIG_FLASH_MAP=y

# 5. Abilita il Flash Circular Buffer (FCB)
CONFIG_FCB=y

# ------------------ Settings Subsystem ------------------
# Abilita il Settings Subsystem
CONFIG_SETTINGS=y

# Seleziona esplicitamente FCB come backend per il Settings Subsystem
CONFIG_SETTINGS_FCB=y

# ------------------ Logging ------------------
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_LOG_MODE_IMMEDIATE=y